SELECT 'FND_FLEX_VALUE_SETS', COUNT(*) FROM ORASARAH_APPS.FND_FLEX_VALUE_SETS
UNION ALL
SELECT 'XLA_TRANSACTION_ENTITIES', COUNT(*) FROM ORASARAH_APPS.XLA_TRANSACTION_ENTITIES
UNION ALL
SELECT 'BOM_DEPARTMENT_RESOURCES', COUNT(*) FROM ORASARAH_APPS.BOM_DEPARTMENT_RESOURCES
UNION ALL
SELECT 'OZF_CLAIM_TYPES_ALL_TL', COUNT(*) FROM ORASARAH_APPS.OZF_CLAIM_TYPES_ALL_TL
UNION ALL
SELECT 'BOM_STRUCTURES_B', COUNT(*) FROM ORASARAH_APPS.BOM_STRUCTURES_B
UNION ALL
SELECT 'XXFT_DISPATCH_HEADERS_ALL', COUNT(*) FROM ORASARAH_APPS.XXFT_DISPATCH_HEADERS_ALL
UNION ALL
SELECT 'XXOZF_SD_PT_HDR_ARCHIVE_E807', COUNT(*) FROM ORASARAH_APPS.XXOZF_SD_PT_HDR_ARCHIVE_E807
UNION ALL
SELECT 'AR_STATEMENT_CYCLES', COUNT(*) FROM ORASARAH_APPS.AR_STATEMENT_CYCLES
UNION ALL
SELECT 'MTL_CATEGORY_SETS_B', COUNT(*) FROM ORASARAH_APPS.MTL_CATEGORY_SETS_B
UNION ALL
SELECT 'AR_LOOKUPS', COUNT(*) FROM ORASARAH_APPS.AR_LOOKUPS
UNION ALL
SELECT 'PO_VENDOR_SITES_ALL', COUNT(*) FROM ORASARAH_APPS.PO_VENDOR_SITES_ALL
UNION ALL
SELECT 'PO_CONTROL_FUNCTIONS', COUNT(*) FROM ORASARAH_APPS.PO_CONTROL_FUNCTIONS
UNION ALL
SELECT 'FND_DOCUMENT_CATEGORIES_TL', COUNT(*) FROM ORASARAH_APPS.FND_DOCUMENT_CATEGORIES_TL
UNION ALL
SELECT 'GL_PERIODS', COUNT(*) FROM ORASARAH_APPS.GL_PERIODS
UNION ALL
SELECT 'AP_INVOICE_DISTRIBUTIONS_ALL', COUNT(*) FROM ORASARAH_APPS.AP_INVOICE_DISTRIBUTIONS_ALL
UNION ALL
SELECT 'WIP_ENTITIES', COUNT(*) FROM ORASARAH_APPS.WIP_ENTITIES
UNION ALL
SELECT 'AR_RECEIPT_METHODS', COUNT(*) FROM ORASARAH_APPS.AR_RECEIPT_METHODS
UNION ALL
SELECT 'AR_BATCHES_ALL', COUNT(*) FROM ORASARAH_APPS.AR_BATCHES_ALL
UNION ALL
SELECT 'XXRPT_SUBL_ACC_SUMMARY_E564', COUNT(*) FROM ORASARAH_APPS.XXRPT_SUBL_ACC_SUMMARY_E564
UNION ALL
SELECT 'XXRPT_ORDER_HIST_D516', COUNT(*) FROM ORASARAH_APPS.XXRPT_ORDER_HIST_D516
UNION ALL
SELECT 'HZ_PARTY_SITES', COUNT(*) FROM ORASARAH_APPS.HZ_PARTY_SITES
UNION ALL
SELECT 'RA_SALESREP_TERRITORIES', COUNT(*) FROM ORASARAH_APPS.RA_SALESREP_TERRITORIES
UNION ALL
SELECT 'RA_TERMS', COUNT(*) FROM ORASARAH_APPS.RA_TERMS
UNION ALL
SELECT 'HZ_ORGANIZATION_PROFILES', COUNT(*) FROM ORASARAH_APPS.HZ_ORGANIZATION_PROFILES
UNION ALL
SELECT 'OZF_FUNDS_UTILIZED_ALL_B', COUNT(*) FROM ORASARAH_APPS.OZF_FUNDS_UTILIZED_ALL_B
UNION ALL
SELECT 'CE_BANK_ACCT_USES_ALL', COUNT(*) FROM ORASARAH_APPS.CE_BANK_ACCT_USES_ALL
UNION ALL
SELECT 'CST_ACTIVITIES', COUNT(*) FROM ORASARAH_APPS.CST_ACTIVITIES
UNION ALL
SELECT 'MTL_SALES_ORDERS', COUNT(*) FROM ORASARAH_APPS.MTL_SALES_ORDERS
UNION ALL
SELECT 'MTL_TRANSACTION_REASONS', COUNT(*) FROM ORASARAH_APPS.MTL_TRANSACTION_REASONS
UNION ALL
SELECT 'AR_CASH_RECEIPT_HISTORY_ALL', COUNT(*) FROM ORASARAH_APPS.AR_CASH_RECEIPT_HISTORY_ALL
UNION ALL
SELECT 'PER_ALL_PEOPLE_F', COUNT(*) FROM ORASARAH_APPS.PER_ALL_PEOPLE_F
UNION ALL
SELECT 'HZ_CUST_PROFILE_AMTS', COUNT(*) FROM ORASARAH_APPS.HZ_CUST_PROFILE_AMTS
UNION ALL
SELECT 'MTL_CATEGORIES_TL', COUNT(*) FROM ORASARAH_APPS.MTL_CATEGORIES_TL
UNION ALL
SELECT 'ECE_TP_GROUP', COUNT(*) FROM ORASARAH_APPS.ECE_TP_GROUP
UNION ALL
SELECT 'AP_SUPPLIER_CONTACTS', COUNT(*) FROM ORASARAH_APPS.AP_SUPPLIER_CONTACTS
UNION ALL
SELECT 'CST_RESOURCE_COSTS', COUNT(*) FROM ORASARAH_APPS.CST_RESOURCE_COSTS
UNION ALL
SELECT 'FA_BOOKS', COUNT(*) FROM ORASARAH_APPS.FA_BOOKS
UNION ALL
SELECT 'MTL_UOM_CONVERSIONS', COUNT(*) FROM ORASARAH_APPS.MTL_UOM_CONVERSIONS
UNION ALL
SELECT 'EGO_MTL_SY_ITEMS_EXT_B', COUNT(*) FROM ORASARAH_APPS.EGO_MTL_SY_ITEMS_EXT_B
UNION ALL
SELECT 'ENG_CHANGE_SUBJECTS', COUNT(*) FROM ORASARAH_APPS.ENG_CHANGE_SUBJECTS
UNION ALL
SELECT 'GL_DATE_PERIOD_MAP', COUNT(*) FROM ORASARAH_APPS.GL_DATE_PERIOD_MAP
UNION ALL
SELECT 'AR_DISTRIBUTIONS_ALL', COUNT(*) FROM ORASARAH_APPS.AR_DISTRIBUTIONS_ALL
UNION ALL
SELECT 'AP_CHECKS_ALL', COUNT(*) FROM ORASARAH_APPS.AP_CHECKS_ALL
UNION ALL
SELECT 'FA_METHODS', COUNT(*) FROM ORASARAH_APPS.FA_METHODS
UNION ALL
SELECT 'CST_ITEM_COST_DETAILS', COUNT(*) FROM ORASARAH_APPS.CST_ITEM_COST_DETAILS
UNION ALL
SELECT 'OE_TRANSACTION_TYPES_TL', COUNT(*) FROM ORASARAH_APPS.OE_TRANSACTION_TYPES_TL
UNION ALL
SELECT 'MRP_FORECAST_DATES', COUNT(*) FROM ORASARAH_APPS.MRP_FORECAST_DATES
UNION ALL
SELECT 'ENG_CHANGE_ACTIONS', COUNT(*) FROM ORASARAH_APPS.ENG_CHANGE_ACTIONS
UNION ALL
SELECT 'oe_pc_attributes_v', COUNT(*) FROM ORASARAH_APPS.oe_pc_attributes_v
UNION ALL
SELECT 'HZ_PARTIES', COUNT(*) FROM ORASARAH_APPS.HZ_PARTIES
UNION ALL
SELECT 'OE_ORDER_SOURCES', COUNT(*) FROM ORASARAH_APPS.OE_ORDER_SOURCES
UNION ALL
SELECT 'MTL_SYSTEM_ITEMS', COUNT(*) FROM ORASARAH_APPS.MTL_SYSTEM_ITEMS
UNION ALL
SELECT 'MTL_CATEGORIES_B', COUNT(*) FROM ORASARAH_APPS.MTL_CATEGORIES_B
UNION ALL
SELECT 'CST_COST_TYPES', COUNT(*) FROM ORASARAH_APPS.CST_COST_TYPES
UNION ALL
SELECT 'XXWIP_DRS_DELAY_RSN_E588', COUNT(*) FROM ORASARAH_APPS.XXWIP_DRS_DELAY_RSN_E588
UNION ALL
SELECT 'GL_LEDGERS', COUNT(*) FROM ORASARAH_APPS.GL_LEDGERS
UNION ALL
SELECT 'MTL_SYSTEM_ITEMS_TL', COUNT(*) FROM ORASARAH_APPS.MTL_SYSTEM_ITEMS_TL
UNION ALL
SELECT 'FND_TERRITORIES_TL', COUNT(*) FROM ORASARAH_APPS.FND_TERRITORIES_TL
UNION ALL
SELECT 'FND_FLEX_VALUES', COUNT(*) FROM ORASARAH_APPS.FND_FLEX_VALUES
UNION ALL
SELECT 'WSH_ROLES', COUNT(*) FROM ORASARAH_APPS.WSH_ROLES
UNION ALL
SELECT 'WSH_CARRIER_SERVICES', COUNT(*) FROM ORASARAH_APPS.WSH_CARRIER_SERVICES
UNION ALL
SELECT 'CN_REVENUE_CLASSES_ALL', COUNT(*) FROM ORASARAH_APPS.CN_REVENUE_CLASSES_ALL
UNION ALL
SELECT 'OE_SALES_CREDIT_TYPES', COUNT(*) FROM ORASARAH_APPS.OE_SALES_CREDIT_TYPES
UNION ALL
SELECT 'FND_FLEX_VALUES_TL', COUNT(*) FROM ORASARAH_APPS.FND_FLEX_VALUES_TL
UNION ALL
SELECT 'XLA_AE_LINES', COUNT(*) FROM ORASARAH_APPS.XLA_AE_LINES
UNION ALL
SELECT 'MTL_ITEM_LOCATIONS', COUNT(*) FROM ORASARAH_APPS.MTL_ITEM_LOCATIONS
UNION ALL
SELECT 'HZ_RELATIONSHIPS', COUNT(*) FROM ORASARAH_APPS.HZ_RELATIONSHIPS
UNION ALL
SELECT 'RA_CUSTOMER_TRX_LINES_ALL', COUNT(*) FROM ORASARAH_APPS.RA_CUSTOMER_TRX_LINES_ALL
UNION ALL
SELECT 'HR_ORGANIZATION_UNITS', COUNT(*) FROM ORASARAH_APPS.HR_ORGANIZATION_UNITS
UNION ALL
SELECT 'FA_LOCATIONS', COUNT(*) FROM ORASARAH_APPS.FA_LOCATIONS
UNION ALL
SELECT 'BOM_OPERATIONAL_ROUTINGS', COUNT(*) FROM ORASARAH_APPS.BOM_OPERATIONAL_ROUTINGS
UNION ALL
SELECT 'AP_TAX_CODES_ALL', COUNT(*) FROM ORASARAH_APPS.AP_TAX_CODES_ALL
UNION ALL
SELECT 'OE_SETS', COUNT(*) FROM ORASARAH_APPS.OE_SETS
UNION ALL
SELECT 'AP_PAYMENT_SCHEDULES_ALL', COUNT(*) FROM ORASARAH_APPS.AP_PAYMENT_SCHEDULES_ALL
UNION ALL
SELECT 'PO_RELEASES_ALL', COUNT(*) FROM ORASARAH_APPS.PO_RELEASES_ALL
UNION ALL
SELECT 'FND_MENUS_TL', COUNT(*) FROM ORASARAH_APPS.FND_MENUS_TL
UNION ALL
SELECT 'ENG_CHANGE_ACTIONS_TL', COUNT(*) FROM ORASARAH_APPS.ENG_CHANGE_ACTIONS_TL
UNION ALL
SELECT 'JTF_RS_RESOURCE_EXTNS_TL', COUNT(*) FROM ORASARAH_APPS.JTF_RS_RESOURCE_EXTNS_TL
UNION ALL
SELECT 'OE_TRANSACTION_TYPES_ALL', COUNT(*) FROM ORASARAH_APPS.OE_TRANSACTION_TYPES_ALL
UNION ALL
SELECT 'WIP_PERIOD_BALANCES', COUNT(*) FROM ORASARAH_APPS.WIP_PERIOD_BALANCES
UNION ALL
SELECT 'MTL_RESERVATIONS', COUNT(*) FROM ORASARAH_APPS.MTL_RESERVATIONS
UNION ALL
SELECT 'RCV_TRANSACTIONS', COUNT(*) FROM ORASARAH_APPS.RCV_TRANSACTIONS
UNION ALL
SELECT 'GL_JE_HEADERS', COUNT(*) FROM ORASARAH_APPS.GL_JE_HEADERS
UNION ALL
SELECT 'XLE_ENTITY_PROFILES', COUNT(*) FROM ORASARAH_APPS.XLE_ENTITY_PROFILES
UNION ALL
SELECT 'OZF_CUST_TRD_PRFLS_ALL', COUNT(*) FROM ORASARAH_APPS.OZF_CUST_TRD_PRFLS_ALL
UNION ALL
SELECT 'XXRRT_CUSTOMER_RELATE_D608_V', COUNT(*) FROM ORASARAH_APPS.XXRRT_CUSTOMER_RELATE_D608_V
UNION ALL
SELECT 'AR_CASH_RECEIPTS_ALL', COUNT(*) FROM ORASARAH_APPS.AR_CASH_RECEIPTS_ALL
UNION ALL
SELECT 'MRP_FORECAST_DESIGNATORS', COUNT(*) FROM ORASARAH_APPS.MRP_FORECAST_DESIGNATORS
UNION ALL
SELECT 'MTL_CYCLE_COUNT_HEADERS', COUNT(*) FROM ORASARAH_APPS.MTL_CYCLE_COUNT_HEADERS
UNION ALL
SELECT 'IBY_PMT_INSTR_USES_ALL', COUNT(*) FROM ORASARAH_APPS.IBY_PMT_INSTR_USES_ALL
UNION ALL
SELECT 'AP_INVOICE_LINES_ALL', COUNT(*) FROM ORASARAH_APPS.AP_INVOICE_LINES_ALL
UNION ALL
SELECT 'GL_DAILY_RATES', COUNT(*) FROM ORASARAH_APPS.GL_DAILY_RATES
UNION ALL
SELECT 'CST_COST_GROUPS', COUNT(*) FROM ORASARAH_APPS.CST_COST_GROUPS
UNION ALL
SELECT 'PO_APPROVAL_LIST_LINES', COUNT(*) FROM ORASARAH_APPS.PO_APPROVAL_LIST_LINES
UNION ALL
SELECT 'HZ_CUST_ACCT_RELATE_ALL', COUNT(*) FROM ORASARAH_APPS.HZ_CUST_ACCT_RELATE_ALL
UNION ALL
SELECT 'HR_OPERATING_UNITS', COUNT(*) FROM ORASARAH_APPS.HR_OPERATING_UNITS
UNION ALL
SELECT 'AR_NOTES', COUNT(*) FROM ORASARAH_APPS.AR_NOTES
UNION ALL
SELECT 'MRP_SR_ASSIGNMENTS', COUNT(*) FROM ORASARAH_APPS.MRP_SR_ASSIGNMENTS
UNION ALL
SELECT 'AR_ADJUSTMENTS_ALL', COUNT(*) FROM ORASARAH_APPS.AR_ADJUSTMENTS_ALL
UNION ALL
SELECT 'HZ_PERSON_PROFILES', COUNT(*) FROM ORASARAH_APPS.HZ_PERSON_PROFILES
UNION ALL
SELECT 'XXRPT_EDI824864_HDR_E752', COUNT(*) FROM ORASARAH_APPS.XXRPT_EDI824864_HDR_E752
UNION ALL
SELECT 'XXRPT_SUBL_ACC_SMRY_HST_E564', COUNT(*) FROM ORASARAH_APPS.XXRPT_SUBL_ACC_SMRY_HST_E564
UNION ALL
SELECT 'WSH_ROLE_PRIVILEGES', COUNT(*) FROM ORASARAH_APPS.WSH_ROLE_PRIVILEGES
UNION ALL
SELECT 'CN_PERIOD_STATUSES_ALL', COUNT(*) FROM ORASARAH_APPS.CN_PERIOD_STATUSES_ALL
UNION ALL
SELECT 'HR_ALL_POSITIONS_F_TL', COUNT(*) FROM ORASARAH_APPS.HR_ALL_POSITIONS_F_TL
UNION ALL
SELECT 'MTL_CYCLE_COUNT_ENTRIES', COUNT(*) FROM ORASARAH_APPS.MTL_CYCLE_COUNT_ENTRIES
UNION ALL
SELECT 'OZF_CLAIM_LINES_UTIL_ALL', COUNT(*) FROM ORASARAH_APPS.OZF_CLAIM_LINES_UTIL_ALL
UNION ALL
SELECT 'FND_PROFILE_OPTIONS', COUNT(*) FROM ORASARAH_APPS.FND_PROFILE_OPTIONS
UNION ALL
SELECT 'CST_MISC_RECONCILIATION', COUNT(*) FROM ORASARAH_APPS.CST_MISC_RECONCILIATION
UNION ALL
SELECT 'WSH_GRANTS', COUNT(*) FROM ORASARAH_APPS.WSH_GRANTS
UNION ALL
SELECT 'AP_EXPENSE_REPORT_HEADERS_ALL', COUNT(*) FROM ORASARAH_APPS.AP_EXPENSE_REPORT_HEADERS_ALL
UNION ALL
SELECT 'JTF_RS_DEFRESROLES_VL', COUNT(*) FROM ORASARAH_APPS.JTF_RS_DEFRESROLES_VL
UNION ALL
SELECT 'GL_PERIOD_STATUSES', COUNT(*) FROM ORASARAH_APPS.GL_PERIOD_STATUSES
UNION ALL
SELECT 'MTL_ITEM_CATEGORIES', COUNT(*) FROM ORASARAH_APPS.MTL_ITEM_CATEGORIES
UNION ALL
SELECT 'RA_CUST_RECEIPT_METHODS', COUNT(*) FROM ORASARAH_APPS.RA_CUST_RECEIPT_METHODS
UNION ALL
SELECT 'CST_COST_ELEMENTS', COUNT(*) FROM ORASARAH_APPS.CST_COST_ELEMENTS
UNION ALL
SELECT 'FA_TRANSACTION_HEADERS', COUNT(*) FROM ORASARAH_APPS.FA_TRANSACTION_HEADERS
UNION ALL
SELECT 'FND_ATTACHED_DOCUMENTS', COUNT(*) FROM ORASARAH_APPS.FND_ATTACHED_DOCUMENTS
UNION ALL
SELECT 'PO_CONTROL_RULES', COUNT(*) FROM ORASARAH_APPS.PO_CONTROL_RULES
UNION ALL
SELECT 'MTL_TXN_SOURCE_TYPES', COUNT(*) FROM ORASARAH_APPS.MTL_TXN_SOURCE_TYPES
UNION ALL
SELECT 'ENG_ECN_APPROVAL_LISTS', COUNT(*) FROM ORASARAH_APPS.ENG_ECN_APPROVAL_LISTS
UNION ALL
SELECT 'MTL_ITEM_CATALOG_GROUPS_B', COUNT(*) FROM ORASARAH_APPS.MTL_ITEM_CATALOG_GROUPS_B
UNION ALL
SELECT 'QP_LIST_HEADERS_B', COUNT(*) FROM ORASARAH_APPS.QP_LIST_HEADERS_B
UNION ALL
SELECT 'XXOZF_SD_PT_LINE_ARCHIVE_E807', COUNT(*) FROM ORASARAH_APPS.XXOZF_SD_PT_LINE_ARCHIVE_E807
UNION ALL
SELECT 'AP_TERMS_TL', COUNT(*) FROM ORASARAH_APPS.AP_TERMS_TL
UNION ALL
SELECT 'PO_AGENTS', COUNT(*) FROM ORASARAH_APPS.PO_AGENTS
UNION ALL
SELECT 'ENG_REVISED_ITEMS', COUNT(*) FROM ORASARAH_APPS.ENG_REVISED_ITEMS
UNION ALL
SELECT 'MTL_LOT_NUMBERS', COUNT(*) FROM ORASARAH_APPS.MTL_LOT_NUMBERS
UNION ALL
SELECT 'WIP_REQUIREMENT_OPERATIONS', COUNT(*) FROM ORASARAH_APPS.WIP_REQUIREMENT_OPERATIONS
UNION ALL
SELECT 'XXWIP_DOWNTIME_E609', COUNT(*) FROM ORASARAH_APPS.XXWIP_DOWNTIME_E609
UNION ALL
SELECT 'HZ_CUST_ACCOUNT_ROLES', COUNT(*) FROM ORASARAH_APPS.HZ_CUST_ACCOUNT_ROLES
UNION ALL
SELECT 'BOM_CALENDAR_DATES', COUNT(*) FROM ORASARAH_APPS.BOM_CALENDAR_DATES
UNION ALL
SELECT 'IBY_EXTERNAL_PAYEES_ALL', COUNT(*) FROM ORASARAH_APPS.IBY_EXTERNAL_PAYEES_ALL
UNION ALL
SELECT 'GL_IMPORT_REFERENCES', COUNT(*) FROM ORASARAH_APPS.GL_IMPORT_REFERENCES
UNION ALL
SELECT 'PO_HEADERS_ALL', COUNT(*) FROM ORASARAH_APPS.PO_HEADERS_ALL
UNION ALL
SELECT 'RA_TERMS_LINES_DISCOUNTS', COUNT(*) FROM ORASARAH_APPS.RA_TERMS_LINES_DISCOUNTS
UNION ALL
SELECT 'ENG_CHANGE_ROUTE_STEPS', COUNT(*) FROM ORASARAH_APPS.ENG_CHANGE_ROUTE_STEPS
UNION ALL
SELECT 'XLA_AE_LINE_ACS', COUNT(*) FROM ORASARAH_APPS.XLA_AE_LINE_ACS
UNION ALL
SELECT 'GL_JE_LINES', COUNT(*) FROM ORASARAH_APPS.GL_JE_LINES
UNION ALL
SELECT 'HZ_CUST_ACCOUNTS_ALL', COUNT(*) FROM ORASARAH_APPS.HZ_CUST_ACCOUNTS_ALL
UNION ALL
SELECT 'MTL_RELATED_ITEMS', COUNT(*) FROM ORASARAH_APPS.MTL_RELATED_ITEMS
UNION ALL
SELECT 'GL_JE_CATEGORIES_TL', COUNT(*) FROM ORASARAH_APPS.GL_JE_CATEGORIES_TL
UNION ALL
SELECT 'QP_PRICING_ATTRIBUTES', COUNT(*) FROM ORASARAH_APPS.QP_PRICING_ATTRIBUTES
UNION ALL
SELECT 'MTL_PHYSICAL_INVENTORIES', COUNT(*) FROM ORASARAH_APPS.MTL_PHYSICAL_INVENTORIES
UNION ALL
SELECT 'FND_DOCUMENTS', COUNT(*) FROM ORASARAH_APPS.FND_DOCUMENTS
UNION ALL
SELECT 'HR_ALL_ORGANIZATION_UNITS_TL', COUNT(*) FROM ORASARAH_APPS.HR_ALL_ORGANIZATION_UNITS_TL
UNION ALL
SELECT 'BOM_OPERATION_SEQUENCES', COUNT(*) FROM ORASARAH_APPS.BOM_OPERATION_SEQUENCES
UNION ALL
SELECT 'WIP_DISCRETE_JOBS', COUNT(*) FROM ORASARAH_APPS.WIP_DISCRETE_JOBS
UNION ALL
SELECT 'WIP_FLOW_SCHEDULES', COUNT(*) FROM ORASARAH_APPS.WIP_FLOW_SCHEDULES
UNION ALL
SELECT 'IBY_EXT_PARTY_PMT_MTHDS', COUNT(*) FROM ORASARAH_APPS.IBY_EXT_PARTY_PMT_MTHDS
UNION ALL
SELECT 'XXRPT_SUBL_AR45_SUMMARY_E564', COUNT(*) FROM ORASARAH_APPS.XXRPT_SUBL_AR45_SUMMARY_E564
UNION ALL
SELECT 'ORG_ACCT_PERIODS', COUNT(*) FROM ORASARAH_APPS.ORG_ACCT_PERIODS
UNION ALL
SELECT 'RA_TERRITORIES', COUNT(*) FROM ORASARAH_APPS.RA_TERRITORIES
UNION ALL
SELECT 'PER_BUSINESS_GROUPS', COUNT(*) FROM ORASARAH_APPS.PER_BUSINESS_GROUPS
UNION ALL
SELECT 'PO_APPROVAL_LIST_HEADERS', COUNT(*) FROM ORASARAH_APPS.PO_APPROVAL_LIST_HEADERS
UNION ALL
SELECT 'OE_HOLD_RELEASES', COUNT(*) FROM ORASARAH_APPS.OE_HOLD_RELEASES
UNION ALL
SELECT 'OZF_SETTLEMENT_DOCS_ALL', COUNT(*) FROM ORASARAH_APPS.OZF_SETTLEMENT_DOCS_ALL
UNION ALL
SELECT 'GL_JE_SOURCES_TL', COUNT(*) FROM ORASARAH_APPS.GL_JE_SOURCES_TL
UNION ALL
SELECT 'XXOZF_SD_PT_HDR_IN_STG_E807', COUNT(*) FROM ORASARAH_APPS.XXOZF_SD_PT_HDR_IN_STG_E807
UNION ALL
SELECT 'ENG_CHANGE_ROUTE_PEOPLE', COUNT(*) FROM ORASARAH_APPS.ENG_CHANGE_ROUTE_PEOPLE
UNION ALL
SELECT 'XXFT_EXPENSE_INCURRED_ALL', COUNT(*) FROM ORASARAH_APPS.XXFT_EXPENSE_INCURRED_ALL
UNION ALL
SELECT 'XXRPT_ORDER_ITEM_HIST_D516', COUNT(*) FROM ORASARAH_APPS.XXRPT_ORDER_ITEM_HIST_D516
UNION ALL
SELECT 'RA_CUST_TRX_LINE_GL_DIST_ALL', COUNT(*) FROM ORASARAH_APPS.RA_CUST_TRX_LINE_GL_DIST_ALL
UNION ALL
SELECT 'HZ_CUST_SITE_USES_ALL', COUNT(*) FROM ORASARAH_APPS.HZ_CUST_SITE_USES_ALL
UNION ALL
SELECT 'BOM_DEPARTMENTS', COUNT(*) FROM ORASARAH_APPS.BOM_DEPARTMENTS
UNION ALL
SELECT 'PO_CONTROL_GROUPS_ALL', COUNT(*) FROM ORASARAH_APPS.PO_CONTROL_GROUPS_ALL
UNION ALL
SELECT 'PO_ASL_ATTRIBUTES', COUNT(*) FROM ORASARAH_APPS.PO_ASL_ATTRIBUTES
UNION ALL
SELECT 'ENG_CHANGE_STATUSES_TL', COUNT(*) FROM ORASARAH_APPS.ENG_CHANGE_STATUSES_TL
UNION ALL
SELECT 'RA_CUST_TRX_LINE_SALESREPS_ALL', COUNT(*) FROM ORASARAH_APPS.RA_CUST_TRX_LINE_SALESREPS_ALL
UNION ALL
SELECT 'AP_BATCHES_ALL', COUNT(*) FROM ORASARAH_APPS.AP_BATCHES_ALL
UNION ALL
SELECT 'QP_LIST_HEADERS_TL', COUNT(*) FROM ORASARAH_APPS.QP_LIST_HEADERS_TL
UNION ALL
SELECT 'PO_LINE_LOCATIONS_ARCHIVE_ALL', COUNT(*) FROM ORASARAH_APPS.PO_LINE_LOCATIONS_ARCHIVE_ALL
UNION ALL
SELECT 'FND_COMMON_LOOKUPS', COUNT(*) FROM ORASARAH_APPS.FND_COMMON_LOOKUPS
UNION ALL
SELECT 'AR_RECEIVABLES_TRX_ALL', COUNT(*) FROM ORASARAH_APPS.AR_RECEIVABLES_TRX_ALL
UNION ALL
SELECT 'AP_EXPENSE_REPORT_LINES_ALL', COUNT(*) FROM ORASARAH_APPS.AP_EXPENSE_REPORT_LINES_ALL
UNION ALL
SELECT 'BOM_STANDARD_OPERATIONS', COUNT(*) FROM ORASARAH_APPS.BOM_STANDARD_OPERATIONS
UNION ALL
SELECT 'FA_BOOK_CONTROLS', COUNT(*) FROM ORASARAH_APPS.FA_BOOK_CONTROLS
UNION ALL
SELECT 'XLA_EVENTS', COUNT(*) FROM ORASARAH_APPS.XLA_EVENTS
UNION ALL
SELECT 'PER_PEOPLE_F', COUNT(*) FROM ORASARAH_APPS.PER_PEOPLE_F
UNION ALL
SELECT 'PO_VENDORS', COUNT(*) FROM ORASARAH_APPS.PO_VENDORS
UNION ALL
SELECT 'OE_DROP_SHIP_SOURCES', COUNT(*) FROM ORASARAH_APPS.OE_DROP_SHIP_SOURCES
UNION ALL
SELECT 'OZF_CLAIM_LINES_ALL', COUNT(*) FROM ORASARAH_APPS.OZF_CLAIM_LINES_ALL
UNION ALL
SELECT 'XXONT_ORD_SUMMARY_E841_EGS', COUNT(*) FROM ORASARAH_APPS.XXONT_ORD_SUMMARY_E841_EGS
UNION ALL
SELECT 'XXOZF_SD_PT_LINE_IN_STG_E807', COUNT(*) FROM ORASARAH_APPS.XXOZF_SD_PT_LINE_IN_STG_E807
UNION ALL
SELECT 'XXWMS_WAVE_CUSTOMERS_E721', COUNT(*) FROM ORASARAH_APPS.XXWMS_WAVE_CUSTOMERS_E721
UNION ALL
SELECT 'HZ_CUST_ACCT_SITES_ALL', COUNT(*) FROM ORASARAH_APPS.HZ_CUST_ACCT_SITES_ALL
UNION ALL
SELECT 'WMS_ZONES_TL', COUNT(*) FROM ORASARAH_APPS.WMS_ZONES_TL
UNION ALL
SELECT 'FA_DISTRIBUTION_HISTORY', COUNT(*) FROM ORASARAH_APPS.FA_DISTRIBUTION_HISTORY
UNION ALL
SELECT 'JTF_RS_RESOURCE_EXTNS', COUNT(*) FROM ORASARAH_APPS.JTF_RS_RESOURCE_EXTNS
UNION ALL
SELECT 'RA_TERMS_TL', COUNT(*) FROM ORASARAH_APPS.RA_TERMS_TL
UNION ALL
SELECT 'WF_USER_ROLE_ASSIGNMENTS', COUNT(*) FROM ORASARAH_APPS.WF_USER_ROLE_ASSIGNMENTS
UNION ALL
SELECT 'WMS_WP_WAVE_LINES', COUNT(*) FROM ORASARAH_APPS.WMS_WP_WAVE_LINES
UNION ALL
SELECT 'CE_STATEMENT_HEADERS', COUNT(*) FROM ORASARAH_APPS.CE_STATEMENT_HEADERS
UNION ALL
SELECT 'MTL_INTERORG_PARAMETERS', COUNT(*) FROM ORASARAH_APPS.MTL_INTERORG_PARAMETERS
UNION ALL
SELECT 'OZF_CLAIMS_ALL', COUNT(*) FROM ORASARAH_APPS.OZF_CLAIMS_ALL
UNION ALL
SELECT 'MRP_SOURCING_RULES', COUNT(*) FROM ORASARAH_APPS.MRP_SOURCING_RULES
UNION ALL
SELECT 'ECE_TP_DETAILS', COUNT(*) FROM ORASARAH_APPS.ECE_TP_DETAILS
UNION ALL
SELECT 'MRP_SR_SOURCE_ORG', COUNT(*) FROM ORASARAH_APPS.MRP_SR_SOURCE_ORG
UNION ALL
SELECT 'PO_LINE_TYPES_B', COUNT(*) FROM ORASARAH_APPS.PO_LINE_TYPES_B
UNION ALL
SELECT 'PO_APPROVED_SUPPLIER_LIST', COUNT(*) FROM ORASARAH_APPS.PO_APPROVED_SUPPLIER_LIST
UNION ALL
SELECT 'MTL_TRANSACTION_TYPES', COUNT(*) FROM ORASARAH_APPS.MTL_TRANSACTION_TYPES
UNION ALL
SELECT 'XXAR_SALESREP_MASTER_I544', COUNT(*) FROM ORASARAH_APPS.XXAR_SALESREP_MASTER_I544
UNION ALL
SELECT 'PER_JOBS_TL', COUNT(*) FROM ORASARAH_APPS.PER_JOBS_TL
UNION ALL
SELECT 'XXWIP_RESOURCE_RUNS_E577', COUNT(*) FROM ORASARAH_APPS.XXWIP_RESOURCE_RUNS_E577
UNION ALL
SELECT 'FND_USER', COUNT(*) FROM ORASARAH_APPS.FND_USER
UNION ALL
SELECT 'AP_INVOICES_ALL', COUNT(*) FROM ORASARAH_APPS.AP_INVOICES_ALL
UNION ALL
SELECT 'BOM_REFERENCE_DESIGNATORS', COUNT(*) FROM ORASARAH_APPS.BOM_REFERENCE_DESIGNATORS
UNION ALL
SELECT 'CE_BANK_ACCOUNTS', COUNT(*) FROM ORASARAH_APPS.CE_BANK_ACCOUNTS
UNION ALL
SELECT 'GL_DAILY_CONVERSION_TYPES', COUNT(*) FROM ORASARAH_APPS.GL_DAILY_CONVERSION_TYPES
UNION ALL
SELECT 'OE_ORDER_LINES_ALL', COUNT(*) FROM ORASARAH_APPS.OE_ORDER_LINES_ALL
union all
SELECT 'RA_CUST_TRX_TYPES_ALL', COUNT(*) FROM ORASARAH_APPS.RA_CUST_TRX_TYPES_ALL
UNION ALL
SELECT 'XXRPT_ITEM_SUMMARY_EGS_D534', COUNT(*) FROM ORASARAH_APPS.XXRPT_ITEM_SUMMARY_EGS_D534
UNION ALL
SELECT 'OE_ORDER_HOLDS_ALL', COUNT(*) FROM ORASARAH_APPS.OE_ORDER_HOLDS_ALL
UNION ALL
SELECT 'WSH_ORG_CARRIER_SERVICES', COUNT(*) FROM ORASARAH_APPS.WSH_ORG_CARRIER_SERVICES
UNION ALL
SELECT 'PO_REQUISITION_LINES_ALL', COUNT(*) FROM ORASARAH_APPS.PO_REQUISITION_LINES_ALL
UNION ALL
SELECT 'WIP_TRANSACTIONS', COUNT(*) FROM ORASARAH_APPS.WIP_TRANSACTIONS
UNION ALL
SELECT 'EGO_ATTR_GROUPS_V', COUNT(*) FROM ORASARAH_APPS.EGO_ATTR_GROUPS_V
UNION ALL
SELECT 'MTL_ONHAND_QUANTITIES_DETAIL', COUNT(*) FROM ORASARAH_APPS.MTL_ONHAND_QUANTITIES_DETAIL
UNION ALL
SELECT 'MTL_CATEGORY_SETS', COUNT(*) FROM ORASARAH_APPS.MTL_CATEGORY_SETS
UNION ALL
SELECT 'HZ_LOCATIONS', COUNT(*) FROM ORASARAH_APPS.HZ_LOCATIONS
UNION ALL
SELECT 'RCV_SHIPMENT_HEADERS', COUNT(*) FROM ORASARAH_APPS.RCV_SHIPMENT_HEADERS
UNION ALL
SELECT 'WMS_WP_WAVE_HEADERS_B', COUNT(*) FROM ORASARAH_APPS.WMS_WP_WAVE_HEADERS_B
UNION ALL
SELECT 'CN_COMMISSION_HEADERS_ALL', COUNT(*) FROM ORASARAH_APPS.CN_COMMISSION_HEADERS_ALL
UNION ALL
SELECT 'RA_BATCH_SOURCES_ALL', COUNT(*) FROM ORASARAH_APPS.RA_BATCH_SOURCES_ALL
UNION ALL
SELECT 'PO_ASL_STATUSES', COUNT(*) FROM ORASARAH_APPS.PO_ASL_STATUSES
UNION ALL
SELECT 'MTL_GENERIC_DISPOSITIONS', COUNT(*) FROM ORASARAH_APPS.MTL_GENERIC_DISPOSITIONS
UNION ALL
SELECT 'QP_LIST_LINES', COUNT(*) FROM ORASARAH_APPS.QP_LIST_LINES
UNION ALL
SELECT 'MTL_ITEM_SUB_INVENTORIES', COUNT(*) FROM ORASARAH_APPS.MTL_ITEM_SUB_INVENTORIES
UNION ALL
SELECT 'RCV_SHIPMENT_LINES', COUNT(*) FROM ORASARAH_APPS.RCV_SHIPMENT_LINES
UNION ALL
SELECT 'FA_ASSET_KEYWORDS', COUNT(*) FROM ORASARAH_APPS.FA_ASSET_KEYWORDS
UNION ALL
SELECT 'FA_MASS_ADDITIONS', COUNT(*) FROM ORASARAH_APPS.FA_MASS_ADDITIONS
UNION ALL
SELECT 'XXFT_DISPATCH_LINES_ALL', COUNT(*) FROM ORASARAH_APPS.XXFT_DISPATCH_LINES_ALL
UNION ALL
SELECT 'MTL_ATP_RULES', COUNT(*) FROM ORASARAH_APPS.MTL_ATP_RULES
UNION ALL
SELECT 'FND_TERRITORIES', COUNT(*) FROM ORASARAH_APPS.FND_TERRITORIES
UNION ALL
SELECT 'XLA_AE_HEADERS', COUNT(*) FROM ORASARAH_APPS.XLA_AE_HEADERS
UNION ALL
SELECT 'AR_COLLECTORS', COUNT(*) FROM ORASARAH_APPS.AR_COLLECTORS
UNION ALL
SELECT 'AP_TERMS_LINES', COUNT(*) FROM ORASARAH_APPS.AP_TERMS_LINES
UNION ALL
SELECT 'FA_ADDITIONS_TL', COUNT(*) FROM ORASARAH_APPS.FA_ADDITIONS_TL
UNION ALL
SELECT 'WSH_FREIGHT_COSTS', COUNT(*) FROM ORASARAH_APPS.WSH_FREIGHT_COSTS
UNION ALL
SELECT 'ENG_CHANGES_EXT_B', COUNT(*) FROM ORASARAH_APPS.ENG_CHANGES_EXT_B
UNION ALL
SELECT 'PO_LOCATION_ASSOCIATIONS_ALL', COUNT(*) FROM ORASARAH_APPS.PO_LOCATION_ASSOCIATIONS_ALL
UNION ALL
SELECT 'MTL_MATERIAL_TRANSACTIONS', COUNT(*) FROM ORASARAH_APPS.MTL_MATERIAL_TRANSACTIONS
UNION ALL
SELECT 'JTF_RS_SALESREPS', COUNT(*) FROM ORASARAH_APPS.JTF_RS_SALESREPS
UNION ALL
SELECT 'ORG_ORGANIZATION_DEFINITIONS', COUNT(*) FROM ORASARAH_APPS.ORG_ORGANIZATION_DEFINITIONS
UNION ALL
SELECT 'FND_RESPONSIBILITY_TL', COUNT(*) FROM ORASARAH_APPS.FND_RESPONSIBILITY_TL
UNION ALL
SELECT 'WIP_OPERATIONS', COUNT(*) FROM ORASARAH_APPS.WIP_OPERATIONS
UNION ALL
SELECT 'HZ_CONTACT_POINTS', COUNT(*) FROM ORASARAH_APPS.HZ_CONTACT_POINTS
UNION ALL
SELECT 'PO_LINES_ALL', COUNT(*) FROM ORASARAH_APPS.PO_LINES_ALL
UNION ALL
SELECT 'XXFT_EXPENSE_CODE_ALL', COUNT(*) FROM ORASARAH_APPS.XXFT_EXPENSE_CODE_ALL
UNION ALL
SELECT 'RA_CUSTOMER_TRX_ALL', COUNT(*) FROM ORASARAH_APPS.RA_CUSTOMER_TRX_ALL
UNION ALL
SELECT 'OE_PRICE_ADJUSTMENTS', COUNT(*) FROM ORASARAH_APPS.OE_PRICE_ADJUSTMENTS
UNION ALL
SELECT 'MTL_CYCLE_COUNT_CLASSES', COUNT(*) FROM ORASARAH_APPS.MTL_CYCLE_COUNT_CLASSES
UNION ALL
SELECT 'WIP_SCHEDULE_GROUPS', COUNT(*) FROM ORASARAH_APPS.WIP_SCHEDULE_GROUPS
UNION ALL
SELECT 'IBY_ACCOUNT_OWNERS', COUNT(*) FROM ORASARAH_APPS.IBY_ACCOUNT_OWNERS
UNION ALL
SELECT 'MRP_ASSIGNMENT_SETS', COUNT(*) FROM ORASARAH_APPS.MRP_ASSIGNMENT_SETS
UNION ALL
SELECT 'MTL_ABC_CLASSES', COUNT(*) FROM ORASARAH_APPS.MTL_ABC_CLASSES
UNION ALL
SELECT 'PO_LINE_LOCATIONS_ALL', COUNT(*) FROM ORASARAH_APPS.PO_LINE_LOCATIONS_ALL
UNION ALL
SELECT 'BOM_COMPONENTS_B', COUNT(*) FROM ORASARAH_APPS.BOM_COMPONENTS_B
UNION ALL
SELECT 'XXOE_LINE_ADDL_INFO_E690', COUNT(*) FROM ORASARAH_APPS.XXOE_LINE_ADDL_INFO_E690
UNION ALL
SELECT 'XXAR_REGION_MASTER_I544', COUNT(*) FROM ORASARAH_APPS.XXAR_REGION_MASTER_I544
UNION ALL
SELECT 'MTL_CATEGORY_SETS_TL', COUNT(*) FROM ORASARAH_APPS.MTL_CATEGORY_SETS_TL
UNION ALL
SELECT 'GL_BUDGET_VERSIONS', COUNT(*) FROM ORASARAH_APPS.GL_BUDGET_VERSIONS
UNION ALL
SELECT 'AR_PAYMENT_SCHEDULES_ALL', COUNT(*) FROM ORASARAH_APPS.AR_PAYMENT_SCHEDULES_ALL
UNION ALL
SELECT 'MTL_PHYSICAL_ADJUSTMENTS', COUNT(*) FROM ORASARAH_APPS.MTL_PHYSICAL_ADJUSTMENTS
UNION ALL
SELECT 'CST_ITEM_COSTS', COUNT(*) FROM ORASARAH_APPS.CST_ITEM_COSTS
UNION ALL
SELECT 'WSH_NEW_DELIVERIES', COUNT(*) FROM ORASARAH_APPS.WSH_NEW_DELIVERIES
UNION ALL
SELECT 'OE_REASONS', COUNT(*) FROM ORASARAH_APPS.OE_REASONS
UNION ALL
SELECT 'ENG_CHANGE_ORDER_TYPES', COUNT(*) FROM ORASARAH_APPS.ENG_CHANGE_ORDER_TYPES
UNION ALL
SELECT 'MTL_PHYSICAL_INVENTORY_TAGS', COUNT(*) FROM ORASARAH_APPS.MTL_PHYSICAL_INVENTORY_TAGS
UNION ALL
SELECT 'XXWSH_MTL_RESERVATIONS_E693', COUNT(*) FROM ORASARAH_APPS.XXWSH_MTL_RESERVATIONS_E693
UNION ALL
SELECT 'MTL_CROSS_REFERENCES_B', COUNT(*) FROM ORASARAH_APPS.MTL_CROSS_REFERENCES_B
UNION ALL
SELECT 'JTF_RS_DEFRESGROUPS_VL', COUNT(*) FROM ORASARAH_APPS.JTF_RS_DEFRESGROUPS_VL
UNION ALL
SELECT 'AP_SUPPLIERS', COUNT(*) FROM ORASARAH_APPS.AP_SUPPLIERS
UNION ALL
SELECT 'GL_CODE_COMBINATIONS', COUNT(*) FROM ORASARAH_APPS.GL_CODE_COMBINATIONS
UNION ALL
SELECT 'MTL_SYSTEM_ITEMS_B', COUNT(*) FROM ORASARAH_APPS.MTL_SYSTEM_ITEMS_B
UNION ALL
SELECT 'WMS_DISPATCHED_TASKS_HISTORY', COUNT(*) FROM ORASARAH_APPS.WMS_DISPATCHED_TASKS_HISTORY
UNION ALL
SELECT 'WMS_WP_WAVE_HEADERS_TL', COUNT(*) FROM ORASARAH_APPS.WMS_WP_WAVE_HEADERS_TL
UNION ALL
SELECT 'ENG_CHANGE_ROUTES', COUNT(*) FROM ORASARAH_APPS.ENG_CHANGE_ROUTES
UNION ALL
SELECT 'PO_LINE_TYPES_TL', COUNT(*) FROM ORASARAH_APPS.PO_LINE_TYPES_TL
UNION ALL
SELECT 'XXAR_AREA_MASTER_I544', COUNT(*) FROM ORASARAH_APPS.XXAR_AREA_MASTER_I544
UNION ALL

SELECT 'HZ_CUST_PROFILE_CLASSES', COUNT(*) FROM ORASARAH_APPS.HZ_CUST_PROFILE_CLASSES
UNION ALL
SELECT 'ZX_LINES', COUNT(*) FROM ORASARAH_APPS.ZX_LINES
UNION ALL
SELECT 'OE_ORDER_HEADERS_ALL', COUNT(*) FROM ORASARAH_APPS.OE_ORDER_HEADERS_ALL
UNION ALL
SELECT 'MTL_SECONDARY_INVENTORIES', COUNT(*) FROM ORASARAH_APPS.MTL_SECONDARY_INVENTORIES
UNION ALL
SELECT 'QP_QUALIFIERS', COUNT(*) FROM ORASARAH_APPS.QP_QUALIFIERS
UNION ALL
SELECT 'BOM_RESOURCES', COUNT(*) FROM ORASARAH_APPS.BOM_RESOURCES
UNION ALL
SELECT 'MRP_FORECAST_ITEMS', COUNT(*) FROM ORASARAH_APPS.MRP_FORECAST_ITEMS
UNION ALL
SELECT 'OE_AUDIT_ATTR_HISTORY', COUNT(*) FROM ORASARAH_APPS.OE_AUDIT_ATTR_HISTORY
UNION ALL
SELECT 'FND_LOOKUP_VALUES', COUNT(*) FROM ORASARAH_APPS.FND_LOOKUP_VALUES
UNION ALL
SELECT 'FND_LOOKUP_TYPES', COUNT(*) FROM ORASARAH_APPS.FND_LOOKUP_TYPES
UNION ALL
SELECT 'WSH_CARRIERS', COUNT(*) FROM ORASARAH_APPS.WSH_CARRIERS
UNION ALL
SELECT 'OZF_RESALE_LINES_ALL', COUNT(*) FROM ORASARAH_APPS.OZF_RESALE_LINES_ALL
UNION ALL
SELECT 'WIP_OPERATION_RESOURCES', COUNT(*) FROM ORASARAH_APPS.WIP_OPERATION_RESOURCES
UNION ALL
SELECT 'IBY_EXT_BANK_ACCOUNTS', COUNT(*) FROM ORASARAH_APPS.IBY_EXT_BANK_ACCOUNTS
UNION ALL
SELECT 'HR_LOCATIONS_ALL', COUNT(*) FROM ORASARAH_APPS.HR_LOCATIONS_ALL
UNION ALL
SELECT 'WSH_DELIVERY_DETAILS', COUNT(*) FROM ORASARAH_APPS.WSH_DELIVERY_DETAILS
UNION ALL
SELECT 'CST_WRITE_OFFS', COUNT(*) FROM ORASARAH_APPS.CST_WRITE_OFFS
UNION ALL
SELECT 'BOM_OPERATION_RESOURCES', COUNT(*) FROM ORASARAH_APPS.BOM_OPERATION_RESOURCES
UNION ALL
SELECT 'MRP_SR_RECEIPT_ORG', COUNT(*) FROM ORASARAH_APPS.MRP_SR_RECEIPT_ORG
UNION ALL
SELECT 'MTL_SAFETY_STOCKS', COUNT(*) FROM ORASARAH_APPS.MTL_SAFETY_STOCKS
UNION ALL
SELECT 'ENG_CHANGE_ORDER_TYPES_TL', COUNT(*) FROM ORASARAH_APPS.ENG_CHANGE_ORDER_TYPES_TL
UNION ALL
SELECT 'XXFT_FARE_POSITION_ALL', COUNT(*) FROM ORASARAH_APPS.XXFT_FARE_POSITION_ALL
UNION ALL
SELECT 'HZ_CUST_ACCOUNTS', COUNT(*) FROM ORASARAH_APPS.HZ_CUST_ACCOUNTS
UNION ALL
SELECT 'GL_BUDGETS', COUNT(*) FROM ORASARAH_APPS.GL_BUDGETS
UNION ALL
SELECT 'MTL_SECONDARY_LOCATORS', COUNT(*) FROM ORASARAH_APPS.MTL_SECONDARY_LOCATORS
UNION ALL
SELECT 'OE_HOLD_DEFINITIONS', COUNT(*) FROM ORASARAH_APPS.OE_HOLD_DEFINITIONS
UNION ALL
SELECT 'EGO_ATTRS_V', COUNT(*) FROM ORASARAH_APPS.EGO_ATTRS_V
UNION ALL
SELECT 'XXWSH_MTL_RESERVATIONS_E842', COUNT(*) FROM ORASARAH_APPS.XXWSH_MTL_RESERVATIONS_E842
UNION ALL
SELECT 'XLA_DISTRIBUTION_LINKS', COUNT(*) FROM ORASARAH_APPS.XLA_DISTRIBUTION_LINKS
UNION ALL
SELECT 'EGO_MTL_SY_ITEMS_EXT_TL', COUNT(*) FROM ORASARAH_APPS.EGO_MTL_SY_ITEMS_EXT_TL
UNION ALL
SELECT 'WMS_ZONE_LOCATORS', COUNT(*) FROM ORASARAH_APPS.WMS_ZONE_LOCATORS
UNION ALL
SELECT 'FA_ADDITIONS_B', COUNT(*) FROM ORASARAH_APPS.FA_ADDITIONS_B
UNION ALL
SELECT 'MTL_CYCLE_COUNT_ITEMS', COUNT(*) FROM ORASARAH_APPS.MTL_CYCLE_COUNT_ITEMS
UNION ALL
SELECT 'FND_PROFILE_OPTION_VALUES', COUNT(*) FROM ORASARAH_APPS.FND_PROFILE_OPTION_VALUES
UNION ALL
SELECT 'XXRPT_ORDER_LINE_HIST_D516', COUNT(*) FROM ORASARAH_APPS.XXRPT_ORDER_LINE_HIST_D516
UNION ALL
SELECT 'HZ_CUSTOMER_PROFILES', COUNT(*) FROM ORASARAH_APPS.HZ_CUSTOMER_PROFILES
UNION ALL
SELECT 'MTL_PARAMETERS', COUNT(*) FROM ORASARAH_APPS.MTL_PARAMETERS
UNION ALL
SELECT 'CST_RECONCILIATION_SUMMARY', COUNT(*) FROM ORASARAH_APPS.CST_RECONCILIATION_SUMMARY
UNION ALL
SELECT 'HZ_ORG_CONTACTS', COUNT(*) FROM ORASARAH_APPS.HZ_ORG_CONTACTS
UNION ALL
SELECT 'OZF_REASON_CODES_ALL_TL', COUNT(*) FROM ORASARAH_APPS.OZF_REASON_CODES_ALL_TL
UNION ALL
SELECT 'AP_INVOICE_PAYMENTS_ALL', COUNT(*) FROM ORASARAH_APPS.AP_INVOICE_PAYMENTS_ALL
UNION ALL
SELECT 'MTL_ITEM_CATALOG_GROUPS_TL', COUNT(*) FROM ORASARAH_APPS.MTL_ITEM_CATALOG_GROUPS_TL
UNION ALL
SELECT 'AP_SUPPLIER_SITES_ALL', COUNT(*) FROM ORASARAH_APPS.AP_SUPPLIER_SITES_ALL
UNION ALL
SELECT 'CE_STATEMENT_LINES', COUNT(*) FROM ORASARAH_APPS.CE_STATEMENT_LINES
UNION ALL
SELECT 'FA_RETIREMENTS', COUNT(*) FROM ORASARAH_APPS.FA_RETIREMENTS
UNION ALL
SELECT 'PO_DISTRIBUTIONS_ALL', COUNT(*) FROM ORASARAH_APPS.PO_DISTRIBUTIONS_ALL
UNION ALL
SELECT 'FA_DEPRN_SUMMARY', COUNT(*) FROM ORASARAH_APPS.FA_DEPRN_SUMMARY
UNION ALL
SELECT 'RA_GROUPING_RULES', COUNT(*) FROM ORASARAH_APPS.RA_GROUPING_RULES
UNION ALL
SELECT 'OE_SYSTEM_PARAMETERS_ALL', COUNT(*) FROM ORASARAH_APPS.OE_SYSTEM_PARAMETERS_ALL
UNION ALL
SELECT 'HR_ALL_ORGANIZATION_UNITS', COUNT(*) FROM ORASARAH_APPS.HR_ALL_ORGANIZATION_UNITS
UNION ALL
SELECT 'MTL_INTERORG_SHIP_METHODS', COUNT(*) FROM ORASARAH_APPS.MTL_INTERORG_SHIP_METHODS
UNION ALL
SELECT 'ECE_TP_HEADERS', COUNT(*) FROM ORASARAH_APPS.ECE_TP_HEADERS
UNION ALL
SELECT 'HR_LOCATIONS_ALL_TL', COUNT(*) FROM ORASARAH_APPS.HR_LOCATIONS_ALL_TL
UNION ALL
SELECT 'HZ_PARTY_SITES_EXT_B', COUNT(*) FROM ORASARAH_APPS.HZ_PARTY_SITES_EXT_B
UNION ALL
SELECT 'FA_CATEGORIES_B', COUNT(*) FROM ORASARAH_APPS.FA_CATEGORIES_B
UNION ALL
SELECT 'OZF_RESALE_BATCHES_ALL', COUNT(*) FROM ORASARAH_APPS.OZF_RESALE_BATCHES_ALL
UNION ALL
SELECT 'XXRPT_BUSINESS_RULES_D758', COUNT(*) FROM ORASARAH_APPS.XXRPT_BUSINESS_RULES_D758
UNION ALL
SELECT 'PO_REQ_DISTRIBUTIONS_ALL', COUNT(*) FROM ORASARAH_APPS.PO_REQ_DISTRIBUTIONS_ALL
UNION ALL
SELECT 'PO_REQUISITION_HEADERS_ALL', COUNT(*) FROM ORASARAH_APPS.PO_REQUISITION_HEADERS_ALL
UNION ALL
SELECT 'ENG_REVISED_COMPONENTS', COUNT(*) FROM ORASARAH_APPS.ENG_REVISED_COMPONENTS
UNION ALL
SELECT 'FND_RESPONSIBILITY', COUNT(*) FROM ORASARAH_APPS.FND_RESPONSIBILITY
UNION ALL
SELECT 'BOM_STD_OP_RESOURCES', COUNT(*) FROM ORASARAH_APPS.BOM_STD_OP_RESOURCES
UNION ALL
SELECT 'MTL_CROSS_REFERENCES_TL', COUNT(*) FROM ORASARAH_APPS.MTL_CROSS_REFERENCES_TL
UNION ALL
SELECT 'CST_DEPARTMENT_OVERHEADS', COUNT(*) FROM ORASARAH_APPS.CST_DEPARTMENT_OVERHEADS
UNION ALL
SELECT 'WMS_LICENSE_PLATE_NUMBERS', COUNT(*) FROM ORASARAH_APPS.WMS_LICENSE_PLATE_NUMBERS
UNION ALL
SELECT 'AP_EXPENSE_REPORTS_ALL', COUNT(*) FROM ORASARAH_APPS.AP_EXPENSE_REPORTS_ALL
UNION ALL
SELECT 'ENG_ENGINEERING_CHANGES', COUNT(*) FROM ORASARAH_APPS.ENG_ENGINEERING_CHANGES
UNION ALL
SELECT 'MTL_MATERIAL_STATUSES_TL', COUNT(*) FROM ORASARAH_APPS.MTL_MATERIAL_STATUSES_TL
UNION ALL
SELECT 'WIP_MOVE_TRANSACTIONS', COUNT(*) FROM ORASARAH_APPS.WIP_MOVE_TRANSACTIONS
UNION ALL
SELECT 'ZX_PARTY_TAX_PROFILE', COUNT(*) FROM ORASARAH_APPS.ZX_PARTY_TAX_PROFILE
UNION ALL
SELECT 'WSH_DELIVERY_ASSIGNMENTS', COUNT(*) FROM ORASARAH_APPS.WSH_DELIVERY_ASSIGNMENTS
UNION ALL
SELECT 'AP_BANK_BRANCHES', COUNT(*) FROM ORASARAH_APPS.AP_BANK_BRANCHES
UNION ALL
SELECT 'OE_HOLD_SOURCES_ALL', COUNT(*) FROM ORASARAH_APPS.OE_HOLD_SOURCES_ALL
UNION ALL
SELECT 'AR_RECEIVABLE_APPLICATIONS_ALL', COUNT(*) FROM ORASARAH_APPS.AR_RECEIVABLE_APPLICATIONS_ALL
UNION ALL
SELECT 'GL_JE_BATCHES', COUNT(*) FROM ORASARAH_APPS.GL_JE_BATCHES
UNION ALL
SELECT 'XXENG_ECO_NTF_AUDIT_E781_EGS', COUNT(*) FROM ORASARAH_APPS.XXENG_ECO_NTF_AUDIT_E781_EGS




